package yeppy.service.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(value = "dataValid") // Tells Jackson to ignore dataValid field generated by DataValidation interface
@JsonInclude(JsonInclude.Include.NON_NULL) // Tells Jackson to ignore all fields with value of NULL
public class LoginResponseModel {
    @JsonProperty(required = true) // Forces this field to be required in the JSON
    private int resultCode;
    @JsonProperty(required = true) // Forces this field to be required in the JSON
    private String message;
    private String userId;

    public LoginResponseModel(){

    }

    @JsonCreator
    public LoginResponseModel(@JsonProperty(value = "resultCode", required = true) int resultCode,
                              @JsonProperty(value = "message", required = true)String message,
                              @JsonProperty(value = "userId", required = true)String userId) {
        this.resultCode = resultCode;
        this.message = message;
        this.userId = userId;
    }

    @JsonCreator
    public LoginResponseModel(int resultCode, String message) {
        this.resultCode = resultCode;
        this.message = message;
        this.userId = null;
    }


    @JsonProperty(value = "resultCode") // Forces Jackson to name the field "resultCode" when serializing this object
    public void setResultCode(int resultCode) {
        this.resultCode=resultCode;
    }

    @JsonProperty(value = "message") // Forces Jackson to name the field "resultCode" when serializing this object
    public void setMessage(String message) {
        this.message=message;
    }

    @JsonProperty(value = "userId") // Forces Jackson to name the field "resultCode" when serializing this object
    public void setUserId(String userId) {
        this.userId=userId;
    }

    @JsonProperty(value = "resultCode")
    public int getResultCode() {
        return resultCode;
    }

    @JsonProperty(value = "message")
    public String getMessage() {
        return message;
    }

    @JsonProperty(value = "userId")
    public String getUserId() {
        return userId;
    }
}